# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import file_components_service_pb2 as file__components__service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in file_components_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class FileComponentsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFileComponents = channel.unary_unary(
                '/FileComponentsService/CreateFileComponents',
                request_serializer=file__components__service__pb2.RepositoryFilePaths.SerializeToString,
                response_deserializer=file__components__service__pb2.FileComponents.FromString,
                _registered_method=True)
        self.GetFileComponents = channel.unary_unary(
                '/FileComponentsService/GetFileComponents',
                request_serializer=file__components__service__pb2.FileComponentIds.SerializeToString,
                response_deserializer=file__components__service__pb2.FileComponents.FromString,
                _registered_method=True)


class FileComponentsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateFileComponents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileComponents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileComponentsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFileComponents': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFileComponents,
                    request_deserializer=file__components__service__pb2.RepositoryFilePaths.FromString,
                    response_serializer=file__components__service__pb2.FileComponents.SerializeToString,
            ),
            'GetFileComponents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileComponents,
                    request_deserializer=file__components__service__pb2.FileComponentIds.FromString,
                    response_serializer=file__components__service__pb2.FileComponents.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileComponentsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FileComponentsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileComponentsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateFileComponents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileComponentsService/CreateFileComponents',
            file__components__service__pb2.RepositoryFilePaths.SerializeToString,
            file__components__service__pb2.FileComponents.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileComponents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileComponentsService/GetFileComponents',
            file__components__service__pb2.FileComponentIds.SerializeToString,
            file__components__service__pb2.FileComponents.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
