# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_components_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66ile_components_service.proto\x1a\x1bgoogle/protobuf/empty.proto\"|\n\rFileComponent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\rrepository_id\x18\x02 \x01(\t\x12\x11\n\tfile_path\x18\x03 \x01(\t\x12\x12\n\nstart_line\x18\x04 \x01(\x05\x12\x10\n\x08\x65nd_line\x18\x05 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\t\".\n\x10\x46ileComponentIds\x12\x1a\n\x12\x66ile_component_ids\x18\x01 \x03(\x05\"@\n\x13RepositoryFilePaths\x12\x15\n\rrepository_id\x18\x01 \x01(\t\x12\x12\n\nfile_paths\x18\x02 \x03(\t\"B\n)DeleteFileComponentsByRepositoryIdRequest\x12\x15\n\rrepository_id\x18\x01 \x01(\t\"b\n5DeleteFileComponentsByRepositoryIdAndFilePathsRequest\x12\x15\n\rrepository_id\x18\x01 \x01(\t\x12\x12\n\nfile_paths\x18\x02 \x03(\t2\xf8\x02\n\x15\x46ileComponentsService\x12>\n\x14\x43reateFileComponents\x12\x14.RepositoryFilePaths\x1a\x0e.FileComponent0\x01\x12\x38\n\x11GetFileComponents\x12\x11.FileComponentIds\x1a\x0e.FileComponent0\x01\x12h\n\"DeleteFileComponentsByRepositoryId\x12*.DeleteFileComponentsByRepositoryIdRequest\x1a\x16.google.protobuf.Empty\x12{\n.DeleteFileComponentsByRepositoryIdAndFilePaths\x12\x36.DeleteFileComponentsByRepositoryIdAndFilePathsRequest\x1a\x11.FileComponentIdsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_components_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILECOMPONENT']._serialized_start=62
  _globals['_FILECOMPONENT']._serialized_end=186
  _globals['_FILECOMPONENTIDS']._serialized_start=188
  _globals['_FILECOMPONENTIDS']._serialized_end=234
  _globals['_REPOSITORYFILEPATHS']._serialized_start=236
  _globals['_REPOSITORYFILEPATHS']._serialized_end=300
  _globals['_DELETEFILECOMPONENTSBYREPOSITORYIDREQUEST']._serialized_start=302
  _globals['_DELETEFILECOMPONENTSBYREPOSITORYIDREQUEST']._serialized_end=368
  _globals['_DELETEFILECOMPONENTSBYREPOSITORYIDANDFILEPATHSREQUEST']._serialized_start=370
  _globals['_DELETEFILECOMPONENTSBYREPOSITORYIDANDFILEPATHSREQUEST']._serialized_end=468
  _globals['_FILECOMPONENTSSERVICE']._serialized_start=471
  _globals['_FILECOMPONENTSSERVICE']._serialized_end=847
# @@protoc_insertion_point(module_scope)
