# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import vector_embedder_service_pb2 as vector__embedder__service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vector_embedder_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class VectorEmbedderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSimilarFileComponentIds = channel.unary_unary(
                '/VectorEmbedderService/GetSimilarFileComponentIds',
                request_serializer=vector__embedder__service__pb2.GetSimilarFileComponentIdsRequest.SerializeToString,
                response_deserializer=vector__embedder__service__pb2.GetSimilarFileComponentIdsResponse.FromString,
                _registered_method=True)
        self.CreateFileComponentVectorEmbeddings = channel.unary_unary(
                '/VectorEmbedderService/CreateFileComponentVectorEmbeddings',
                request_serializer=vector__embedder__service__pb2.CreateFileComponentVectorEmbeddingsRequest.SerializeToString,
                response_deserializer=vector__embedder__service__pb2.CreateFileComponentVectorEmbeddingsResponse.FromString,
                _registered_method=True)
        self.DeleteFileComponentVectorEmbeddingsByRepositoryId = channel.unary_unary(
                '/VectorEmbedderService/DeleteFileComponentVectorEmbeddingsByRepositoryId',
                request_serializer=vector__embedder__service__pb2.DeleteFileComponentVectorEmbeddingsByRepositoryIdRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteFileComponentVectorEmbeddingsByRepositoryIdAndFileComponentIds = channel.unary_unary(
                '/VectorEmbedderService/DeleteFileComponentVectorEmbeddingsByRepositoryIdAndFileComponentIds',
                request_serializer=vector__embedder__service__pb2.DeleteFileComponentVectorEmbeddingsByRepositoryIdAndFileComponentIdsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class VectorEmbedderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSimilarFileComponentIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFileComponentVectorEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFileComponentVectorEmbeddingsByRepositoryId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFileComponentVectorEmbeddingsByRepositoryIdAndFileComponentIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorEmbedderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSimilarFileComponentIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimilarFileComponentIds,
                    request_deserializer=vector__embedder__service__pb2.GetSimilarFileComponentIdsRequest.FromString,
                    response_serializer=vector__embedder__service__pb2.GetSimilarFileComponentIdsResponse.SerializeToString,
            ),
            'CreateFileComponentVectorEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFileComponentVectorEmbeddings,
                    request_deserializer=vector__embedder__service__pb2.CreateFileComponentVectorEmbeddingsRequest.FromString,
                    response_serializer=vector__embedder__service__pb2.CreateFileComponentVectorEmbeddingsResponse.SerializeToString,
            ),
            'DeleteFileComponentVectorEmbeddingsByRepositoryId': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFileComponentVectorEmbeddingsByRepositoryId,
                    request_deserializer=vector__embedder__service__pb2.DeleteFileComponentVectorEmbeddingsByRepositoryIdRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteFileComponentVectorEmbeddingsByRepositoryIdAndFileComponentIds': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFileComponentVectorEmbeddingsByRepositoryIdAndFileComponentIds,
                    request_deserializer=vector__embedder__service__pb2.DeleteFileComponentVectorEmbeddingsByRepositoryIdAndFileComponentIdsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VectorEmbedderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VectorEmbedderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorEmbedderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSimilarFileComponentIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VectorEmbedderService/GetSimilarFileComponentIds',
            vector__embedder__service__pb2.GetSimilarFileComponentIdsRequest.SerializeToString,
            vector__embedder__service__pb2.GetSimilarFileComponentIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFileComponentVectorEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VectorEmbedderService/CreateFileComponentVectorEmbeddings',
            vector__embedder__service__pb2.CreateFileComponentVectorEmbeddingsRequest.SerializeToString,
            vector__embedder__service__pb2.CreateFileComponentVectorEmbeddingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFileComponentVectorEmbeddingsByRepositoryId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VectorEmbedderService/DeleteFileComponentVectorEmbeddingsByRepositoryId',
            vector__embedder__service__pb2.DeleteFileComponentVectorEmbeddingsByRepositoryIdRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFileComponentVectorEmbeddingsByRepositoryIdAndFileComponentIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VectorEmbedderService/DeleteFileComponentVectorEmbeddingsByRepositoryIdAndFileComponentIds',
            vector__embedder__service__pb2.DeleteFileComponentVectorEmbeddingsByRepositoryIdAndFileComponentIdsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
