# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector_embedder_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dvector_embedder_service.proto\"H\n*CreateFileComponentVectorEmbeddingsRequest\x12\x1a\n\x12\x66ile_component_ids\x18\x01 \x03(\x05\"Z\n+CreateFileComponentVectorEmbeddingsResponse\x12+\n#file_component_vector_embedding_ids\x18\x01 \x03(\t\"R\n!GetSimilarFileComponentIdsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\"@\n\"GetSimilarFileComponentIdsResponse\x12\x1a\n\x12\x66ile_component_ids\x18\x01 \x03(\x05\x32\x81\x02\n\x15VectorEmbedderService\x12\x65\n\x1aGetSimilarFileComponentIds\x12\".GetSimilarFileComponentIdsRequest\x1a#.GetSimilarFileComponentIdsResponse\x12\x80\x01\n#CreateFileComponentVectorEmbeddings\x12+.CreateFileComponentVectorEmbeddingsRequest\x1a,.CreateFileComponentVectorEmbeddingsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_embedder_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEFILECOMPONENTVECTOREMBEDDINGSREQUEST']._serialized_start=33
  _globals['_CREATEFILECOMPONENTVECTOREMBEDDINGSREQUEST']._serialized_end=105
  _globals['_CREATEFILECOMPONENTVECTOREMBEDDINGSRESPONSE']._serialized_start=107
  _globals['_CREATEFILECOMPONENTVECTOREMBEDDINGSRESPONSE']._serialized_end=197
  _globals['_GETSIMILARFILECOMPONENTIDSREQUEST']._serialized_start=199
  _globals['_GETSIMILARFILECOMPONENTIDSREQUEST']._serialized_end=281
  _globals['_GETSIMILARFILECOMPONENTIDSRESPONSE']._serialized_start=283
  _globals['_GETSIMILARFILECOMPONENTIDSRESPONSE']._serialized_end=347
  _globals['_VECTOREMBEDDERSERVICE']._serialized_start=350
  _globals['_VECTOREMBEDDERSERVICE']._serialized_end=607
# @@protoc_insertion_point(module_scope)
