# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector_embedder_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dvector_embedder_service.proto\"C\n%BatchVectorEmbedFileComponentsRequest\x12\x1a\n\x12\x66ile_component_ids\x18\x01 \x03(\x05\"U\n&BatchVectorEmbedFileComponentsResponse\x12+\n#file_component_vector_embedding_ids\x18\x01 \x03(\x05\x32\x8a\x01\n\x15VectorEmbedderService\x12q\n\x1e\x42\x61tchVectorEmbedFileComponents\x12&.BatchVectorEmbedFileComponentsRequest\x1a\'.BatchVectorEmbedFileComponentsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_embedder_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATCHVECTOREMBEDFILECOMPONENTSREQUEST']._serialized_start=33
  _globals['_BATCHVECTOREMBEDFILECOMPONENTSREQUEST']._serialized_end=100
  _globals['_BATCHVECTOREMBEDFILECOMPONENTSRESPONSE']._serialized_start=102
  _globals['_BATCHVECTOREMBEDFILECOMPONENTSRESPONSE']._serialized_end=187
  _globals['_VECTOREMBEDDERSERVICE']._serialized_start=190
  _globals['_VECTOREMBEDDERSERVICE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
